<tr class="<?php echo ($this->partialCounter%2)?'even':'odd';?>">        
    <td><?php echo $this->id; ?></td>
    <td><?php echo $this->name; ?></td>
    <td><?php echo $this->email; ?></td>
    <td><?php echo $this->fee; ?></td>  
    <td><?php echo $this->broker_name; ?></td>  
    <td>
        <?php if(Core_Acl::isUserAllowed('default:clients', 'edit')):?>
        <a href="<?php echo $this->url(
            array(
                'controller'=> 'clients', 
                'action'=>'edit', 
                'id' => $this->id
            ),
            null, 
            true
        );?>"><?php echo $this->translate('EDIT'); ?></a>
        <?php endif;?>
        <?php if(!Core_Acl::isUserAllowed('default:clients', 'edit') && Core_Acl::isUserAllowed('default:clients', 'view')):?>
        <a href="<?php echo $this->url(
            array(
                'controller'=> 'clients', 
                'action'=>'view', 
                'id' => $this->id
            ),
            null, 
            true
        );?>"><?php echo $this->translate('VIEW');?></a>
        <?php endif;?>
        <?php if(Core_Acl::isUserAllowed('default:clients', 'delete')):?>
        &nbsp;
        <a href="<?php echo $this->url(
            array(
                'controller'=> 'clients', 
                'action'=>'delete', 
                'id' => $this->id
            ),
            null, 
            true
        );?>"><?php echo $this->translate('DELETE'); ?></a>  
        <?php endif;?>
    </td>
</tr>
