<tr class="<?php echo ($this->partialCounter%2)?'even':'odd';?>">        
    <td><?php echo $this->partialCounter; ?></td>
    <td><?php echo $this->email; ?></td>
    <td><?php echo $this->created; ?></td>            
    <td>
        <?php if(Core_Acl::isUserAllowed('default:users', 'add')):?>
        <a href="<?php echo $this->url(
            array(
                'controller'=> 'users', 
                'action'=>'add', 
                'email' => $this->email
            ),
            null, 
            true
        );?>"><?php echo $this->translate('ADD_USER'); ?></a>
        <?php endif;?>    
        <?php if(Core_Acl::isUserAllowed('default:users', 'delete')):?>
        &nbsp;
        <a href="<?php echo $this->url(
            array(
                'controller'=> 'account-requests', 
                'action'=>'delete', 
                'id' => $this->id
            ),
            null, 
            true
        );?>"><?php echo $this->translate('DELETE'); ?></a>  
        <?php endif;?>
    </td>
</tr>
