<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pl" xml:lang="pl">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>
        <?php echo $this->headLink()
               ->prependStylesheet($this->baseUrl().'/css/general.css')
               ->appendStylesheet($this->baseUrl().'/css/admin.css'); ?>
        <?php echo $this->jQuery();?>
        <?php echo $this->headScript()
                ->appendFile('/js/lib/core.js'); ?>
    </head>
    <body>
        <div id="all">
            <div id="header">
                <div class="inner">
                    <?php echo $this->partial('partials/header.phtml'); ?>
                </div>
            </div>
            <div id="navigation">
                <?php echo $this->navigation()->menu();?>
            </div>
            <div id="main">
                <div class="inner">
                    <h1 class="title"><?php echo $this->placeholder('title'); ?></h1>
                    <?php echo $this->placeholder('system-messages');?>
                    <?php echo $this->layout()->content; ?>
                    <div id="footer">
                        <?php echo $this->partial('partials/footer.phtml'); ?>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>